- name: Expo-Unsigned-IPA
  # You may pin to the exact commit or the version.
  # uses: gamekiller2048/Expo-Unsigned-IPA@4228e289556fca6253e400123b7e3d3832483541
  uses: gamekiller2048/Expo-Unsigned-IPA@v1
  with:
    # name of expo project
    PROJECT_NAME: 
    # whether to clear the last cache
    CLEAR_CACHE: # optional, default is false
